QT_PLUGIN.qdarwinbluetoothpermission.TYPE = permissions
QT_PLUGIN.qdarwinbluetoothpermission.EXTENDS = -
QT_PLUGIN.qdarwinbluetoothpermission.DEPENDS = core
QT_PLUGIN.qdarwinbluetoothpermission.CLASS_NAME = QDarwinBluetoothPermissionPlugin
QT_PLUGIN.qdarwinbluetoothpermission.module_config = v2 staticlib
QT_PLUGINS += qdarwinbluetoothpermission
QT_PLUGIN.qdarwinbluetoothpermission.usage_descriptions = NSBluetoothAlwaysUsageDescription
QT_PLUGIN.qdarwinbluetoothpermission.request_flag = 