/* This file was generated by syncqt. */
#ifndef QT_QTPROTOBUF_VERSION_H
#define QT_QTPROTOBUF_VERSION_H

#define QTPROTOBUF_VERSION_STR "6.6.1"

#define QTPROTOBUF_VERSION 0x060601

#endif // QT_QTPROTOBUF_VERSION_H
