/* This file was generated by syncqt. */
#ifndef QT_QTJSONRPC_VERSION_H
#define QT_QTJSONRPC_VERSION_H

#define QTJSONRPC_VERSION_STR "6.6.1"

#define QTJSONRPC_VERSION 0x060601

#endif // QT_QTJSONRPC_VERSION_H
