QT.coap_private.VERSION = 6.6.0
QT.coap_private.name = QtCoap
QT.coap_private.module =
QT.coap_private.libs = $$QT_MODULE_LIB_BASE
QT.coap_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCoap/6.6.0 $$QT_MODULE_INCLUDE_BASE/QtCoap/6.6.0/QtCoap
QT.coap_private.frameworks = 
QT.coap_private.depends = core_private network coap
QT.coap_private.uses = 
QT.coap_private.module_config = v2 staticlib internal_module
QT.coap_private.enabled_features = 
QT.coap_private.disabled_features = 
